version: '3'
services:
  graph-node:
    image: >-
      graphprotocol/graph-node@sha256:688f00bd12d619c3cc8c8c0b11aee47d61b5f5e36d62ad002e5ce1e7f3c116f2
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
    links:
      - ipfs
      - postgres
      - ganache
    environment:
      postgres_host: 'postgres:5432'
      postgres_user: postgres
      postgres_pass: letmein
      postgres_db: postgres
      ipfs: 'ipfs:5001'
      ethereum: 'private:http://ganache:8545'
      GRAPH_IPFS_TIMEOUT: '2'
      GRAPH_MAX_IPFS_FILE_BYTES: '120000'
  ipfs:
    build: docker/ipfs
    ports:
      - '5001:5001'
  postgres:
    build: docker/postgres
    ports:
      - '5434:5432'
    environment:
      POSTGRES_PASSWORD: letmein
  ganache:
    image: 'daostack/migration:0.0.1-rc.23-v2'
    ports:
      - '8545:8545'
